name: Build NuGet package for Unity SDK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8

      - name: Pack NuGet package
        shell: pwsh
        run: |
          cd Unity/NuGet
          ./pack.ps1

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: VedalAI.NeuroSdk.Unity
          path: Unity/NuGet/bin/Release/*.nupkg